export enum AuditEvent {
  AUTHENTICATION_SUCCEEDED = 'AUTHENTICATION_SUCCEEDED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  IDENTITY_VIEWED = 'IDENTITY_VIEWED',
  RISK_EVALUATION_REQUESTED = 'RISK_EVALUATION_REQUESTED',
  REPORT_REQUESTED = 'REPORT_REQUESTED'
}

export enum Role {
  CONSUMER = 'CONSUMER', SME = 'SME', LENDER = 'LENDER', BUSINESS = 'BUSINESS', ADMIN = 'ADMIN'
}

export enum ConsentStatus {
  PENDING = 'PENDING', GRANTED = 'GRANTED', REVOKED = 'REVOKED', EXPIRED = 'EXPIRED'
}

export enum RiskRecommendation {
  REVIEW_RECOMMENDED = 'REVIEW_RECOMMENDED',
  ADDITIONAL_INFORMATION_RECOMMENDED = 'ADDITIONAL_INFORMATION_RECOMMENDED',
  MANUAL_ASSESSMENT_RECOMMENDED = 'MANUAL_ASSESSMENT_RECOMMENDED'
}
